apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
type: Opaque
stringData:
  MONGO_URI: {{ .Values.secrets.mongoUri | quote }}
  MONGO_USER: {{ .Values.secrets.mongoUser | quote }}
  MONGO_PASSWORD: {{ .Values.secrets.mongoPassword | quote }}
